
let DATA=__DATAJSON__.map((r,i)=>({...r,_id:i+1}));
let page='overview', seq=DATA.length, fstep=1, draft={}, fichaTab=0, current=null;
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}
function badge(s){const m=MOD.statusColors[s]||'#5B6470';return '<span class="pill" style="background:'+m+'22;color:'+m+';border:1px solid '+m+'55">'+s+'</span>';}
function go(p){page=p;current=null;render();}
function renderSB(){document.getElementById('sb').innerHTML=MOD.nav.map(n=>'<button class="navitem'+(page===n.id?' on':'')+'" onclick="go(\''+n.id+'\')"><span>'+n.icon+'</span>'+n.label+'</button>').join('')+'<div style="margin-top:auto;padding:12px;font-size:10.5px;color:var(--soft)">TERRA+ · '+MOD.code+'<br>v1.0 · '+DATA.length+' registros</div>';}
function kpis(){return '<div class="kpis">'+MOD.kpis.map(k=>'<div class="kpi"><div class="kpi-l">'+k.l+'</div><div class="kpi-v">'+k.v+'</div><div class="kpi-d" style="color:'+(k.up?'var(--low)':'var(--high)')+'">'+k.d+'</div></div>').join('')+'</div>';}
function miniTable(rows){return '<table class="tbl"><thead><tr>'+MOD.cols.map(c=>'<th>'+c.h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+MOD.cols.map(c=>'<td>'+(c.k==='status'?badge(r[c.k]):(r[c.k]??'—'))+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function pageOverview(){return '<div class="crumb">Início › Visão Geral</div><h1>'+MOD.name+'</h1><p class="sub">'+MOD.desc+'</p>'+kpis()+'<div class="card"><h3>Fluxo do módulo</h3><div class="flow">'+MOD.flow.map((f,i)=>'<div class="flow-step"><span class="fn">'+(i+1)+'</span>'+f+'</div>').join('<span class="farr">→</span>')+'</div></div><div class="grid2"><div class="card"><h3>Registros recentes</h3>'+miniTable(DATA.slice(0,5))+'</div><div class="card"><h3>Agentes de IA</h3>'+MOD.agents.map(a=>'<div class="agent"><b>'+a.n+'</b><span>'+a.d+'</span></div>').join('')+'</div></div>';}
function pageList(){return '<div class="crumb">'+MOD.short+' › Registros</div><div class="rowflex"><h1>Registros</h1><button class="btn primary" onclick="openNew()">＋ Novo</button></div><div class="card"><table class="tbl"><thead><tr>'+MOD.cols.map(c=>'<th>'+c.h+'</th>').join('')+'<th>Ações</th></tr></thead><tbody>'+DATA.map(r=>'<tr>'+MOD.cols.map(c=>'<td>'+(c.k==='status'?badge(r[c.k]):(r[c.k]??'—'))+'</td>').join('')+'<td class="nowrap"><button class="lnk" onclick="openFicha('+r._id+')">Abrir</button> · <button class="lnk" onclick="openEdit('+r._id+')">Editar</button></td></tr>').join('')+'</tbody></table></div>';}
function pageKanban(){return '<div class="crumb">'+MOD.short+' › Produção</div><h1>Kanban de produção</h1><p class="sub">Arraste mentalmente entre as fases — clique para abrir a ficha.</p><div class="kanban">'+MOD.kanban.map(col=>{const items=DATA.filter(r=>r.status===col);return '<div class="kbcol"><div class="kbh">'+col+' <span class="cnt">'+items.length+'</span></div>'+items.map(r=>'<div class="kbcard" onclick="openFicha('+r._id+')"><b>'+r[MOD.cols[0].k]+'</b><div style="font-size:11px;color:var(--muted)">'+(r[MOD.cols[1].k]||'')+'</div></div>').join('')+'</div>';}).join('')+'</div>';}
function pageValid(){return '<div class="crumb">'+MOD.short+' › Qualidade</div><h1>Validação & Qualidade</h1><div class="card"><h3>Regras automáticas</h3>'+MOD.rules.map(r=>'<div class="ruleln"><span class="dot" style="background:'+(r.ok?'var(--low)':'var(--crit)')+'"></span><b>'+r.n+'</b><span style="margin-left:auto;color:var(--muted)">'+r.s+'</span></div>').join('')+'</div><div class="card"><h3>Score de qualidade por registro</h3>'+DATA.map(r=>{const sc=60+((r._id*17)%40);return '<div class="scoreln"><b style="min-width:200px">'+r[MOD.cols[0].k]+'</b><div class="bar"><i style="width:'+sc+'%;background:'+(sc>80?'var(--low)':sc>65?'var(--med)':'var(--crit)')+'"></i></div><span>'+sc+'%</span></div>';}).join('')+'</div>';}
function openNew(){current=null;draft={};fstep=1;page='form';render();}
function openEdit(id){current=DATA.find(r=>r._id===id);draft={...current};fstep=1;page='form';render();}
function fld(f){const v=draft[f.k]??'';let input;if(f.t==='select')input='<select onchange="draft[\''+f.k+'\']=this.value">'+f.o.map(o=>'<option'+(o===v?' selected':'')+'>'+o+'</option>').join('')+'</select>';else if(f.t==='textarea')input='<textarea rows="3" oninput="draft[\''+f.k+'\']=this.value">'+v+'</textarea>';else input='<input value="'+v+'" oninput="draft[\''+f.k+'\']=this.value">';return '<div class="fld"'+(f.full?' style="grid-column:1/3"':'')+'><label>'+f.l+'</label>'+input+'</div>';}
function renderForm(){const steps=MOD.formSteps;const fields=steps[fstep-1].fields.map(f=>fld(f)).join('');document.getElementById('main').innerHTML='<div class="crumb">'+MOD.short+' › '+(current?'Editar registro':'Novo registro')+'</div><h1>'+(current?'Editar — '+(draft[MOD.cols[0].k]||''):'Novo '+MOD.entity)+'</h1><div class="wsteps">'+steps.map((s,i)=>'<div class="'+(i+1===fstep?'on':(i+1<fstep?'done':''))+'">'+(i+1)+'. '+s.t+'</div>').join('')+'</div><div class="card"><h3>'+steps[fstep-1].t+'</h3><div class="fgrid">'+fields+'</div></div><div class="rowflex"><button class="btn" onclick="go(\'list\')">Cancelar</button><div style="margin-left:auto;display:flex;gap:8px">'+(fstep>1?'<button class="btn" onclick="fmove(-1)">← Voltar</button>':'')+(fstep<steps.length?'<button class="btn primary" onclick="fmove(1)">Avançar →</button>':'<button class="btn primary" onclick="saveForm()">💾 Salvar</button>')+'</div></div>';}
function fmove(d){fstep+=d;renderForm();}
function saveForm(){if(current){Object.assign(current,draft);toast('Registro atualizado ✔');}else{seq++;DATA.unshift({...draft,_id:seq,status:draft.status||MOD.kanban[0]});toast('Registro criado ✔');}go('list');}
function openFicha(id){current=DATA.find(r=>r._id===id);fichaTab=0;page='ficha';render();}
function setTab(i){fichaTab=i;renderFicha();}
function fichaBody(t,r){if(t.dl)return '<dl class="dl">'+t.dl.map(p=>'<div><dt>'+p[0]+'</dt><dd>'+(r[p[1]]??'—')+'</dd></div>').join('')+'</dl>';return '<p style="color:var(--muted);font-size:12.5px;line-height:1.7">Seção <b style="color:var(--ink)">'+t.t+'</b> do registro <b style="color:var(--ink)">'+r[MOD.cols[0].k]+'</b>. '+t.txt+'</p>';}
function renderFicha(){const r=current,tabs=MOD.fichaTabs;document.getElementById('main').innerHTML='<div class="crumb">'+MOD.short+' › Registros › '+(r[MOD.cols[0].k])+'</div><div class="rowflex"><h1>'+r[MOD.cols[0].k]+'</h1><div style="margin-left:auto;display:flex;gap:8px"><button class="btn" onclick="openEdit('+r._id+')">✏️ Editar</button><button class="btn primary" onclick="toast(\'Relatório PDF gerado ✔\')">📄 Relatório</button></div></div>'+badge(r.status)+'<div class="tabbar" style="margin-top:14px">'+tabs.map((t,i)=>'<button class="'+(i===fichaTab?'on':'')+'" onclick="setTab('+i+')">'+t.t+'</button>').join('')+'</div><div class="card">'+fichaBody(tabs[fichaTab],r)+'</div>';}
function render(){renderSB();if(page==='form'){renderForm();return;}if(page==='ficha'){renderFicha();return;}const map={overview:pageOverview,list:pageList,kanban:pageKanban,valid:pageValid};document.getElementById('main').innerHTML=(map[page]||pageOverview)();}
render();
